build-job:
  stage: build
  tags:
    - cluster
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - apt update && apt install -y git
    - pwd && ls -al 
    - git branch && git status
  only:
    - devops-k8s

test-job1:
  stage: test
  tags:
    - cluster
  script:
    - echo "This job tests something"
  only:
    - devops-k8s

test-job2:
  stage: test
  tags:
    - cluster
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
  only:
    - devops-k8s
    
deploy-prod:
  stage: deploy
  tags:
    - cluster
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  only:
    - devops-k8s
