apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: pgpool/pgpool:4.2.2
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: carrick-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: carrick-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: pgpool-config
          mountPath: /config
#      - name: pgpool-stats
#        image: pgpool/pgpool2_exporter:1.0
#        env:
#        - name: POSTGRES_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: hippo-postgres-secret
#              key: postrges
#        - name: POSTGRES_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: hippo-postgres-secret
#              key: lecmB64Mld4hiebd
#        - name: PGPOOL_SERVICE
#          value: "localhost"
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
spec:
  type: LoadBalancer
  selector:
    app: pgpool
  ports:
  - name: pgpool-port
    protocol: TCP
    port: 9999
    targetPort: 9999
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: pgpool-stats
#  labels:
#    app: pgpool-stats
#  annotations:
#    prometheus.io/path: /metrics
#    prometheus.io/port: "9719"
#    prometheus.io/scrape: "true"
#spec:
#  selector:
#    app: pgpool
#  ports:
#  - name: pgpool-stats-port
#    protocol: TCP
#    port: 9719
#    targetPort: 9719
